jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code (JCasC)\n\n"

  # Configure Jenkins admin users to avoid creating one in 1st init 
  securityRealm:
    local:
      allowsSignup: false # Disable users from creating account through web interface
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  
  clouds:
    # Configure Docker cloud for containerized builds
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"
        templates:
          - labelString: "docker-agent"
            dockerTemplateBase:
              image: "jenkins/agent"
              mounts:
                - "type=tmpfs,destination=/run"
                - "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock"
            remoteFs: "/home/jenkins/agent"
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "10"
            retentionStrategy:
              idleMinutes: 1


# Force enable Dark theme
appearance:
  themeManager:
    disableUserThemes: true
    theme: "darkSystem" # use 'dark' for forcing the dark theme regardless of OS settings

# Setup seed job
jobs:
  - script: |
      job('seed') {
        scm {
          git {
            remote {
              url 'https://github.com/hainenber/jenkins-labs.git'
            }
          }
        }
        steps {
          jobDsl {
            targets 'jobs/**/*.groovy'
          }
        }
      }
