jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code (JCasC)\n\n"

  # Configure Jenkins admin users to avoid creating one in 1st init 
  securityRealm:
    local:
      allowsSignup: false # Disable users from creating account through web interface
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  
  # Nodes
  # A temporarily permanent node used to, setup beforehand by Multipass (Java installation, pubkey trust, et cetera)
  # TODO: Configure the node with CloudInit
  nodes:
    - permanent:
        name: 'java-app-builder-1'
        labelString: 'java-app-builder'
        remoteFS: '/home/jenkins'
        numExecutors: 1
        launcher:
          ssh:
            host: '192.168.71.3'
            credentialsId: multipass-agent-ssh-username-with-private-key
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                  requireInitialManualTrust: false
  
# Secrets 
# 1. (SSH username with private key) Credential to register Multipass VMs as Jenkins agents 
credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: multipass-agent-ssh-username-with-private-key
              username: jenkins
              privateKeySource:
                directEntry:
                  privateKey: ${file:/secrets/multipass-agent-ssh-key}

# Force enable Dark theme
appearance:
  themeManager:
    disableUserThemes: true
    theme: "darkSystem" # use 'dark' for forcing the dark theme regardless of OS settings

# Setup seed job
# Source: https://gerg.dev/2020/06/creating-a-job-dsl-seed-job-with-jcasc/
jobs:
  - script: |
      job('seed') {
        scm {
          git {
            remote {
              url 'https://github.com/hainenber/jenkins-labs.git'
            }
          }
        }
        steps {
          jobDsl {
            targets 'jobs/**/*.groovy'
          }
        }
      }
