name: validate-yaml

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML files
        id: validate-yaml
        uses: GrantBirki/json-yaml-validator@v3.2.1
